language: go

go:
  - 1.6

before_install:

script:
  - go test ./sim -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"