// Code generated by "stringer -type=Color"; DO NOT EDIT.

package orgnetsim

import "fmt"

const _Color_name = "GreyRedGreenBlueYellowOrangePurple"

var _Color_index = [...]uint8{0, 4, 7, 12, 16, 22, 28, 34}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
