name: Go Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.16'

    - name: Build
      run: |
        set -e
        cd web
        npm install
        npm run-script build
        cp -r build/* ../orgnetsim/web/

        cd ../orgnetsim
        go build
        cd ..

    - name: Test
      run: |
        ./test.sh
    
    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
