name: Go Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.16'

    - name: Build
      run: |
      set -e

      cd web
      npm run-script build
      cp -r build/* ../orgnetsim/web/

      cd ../orgnetsim
      go build

    - name: Test
      run: |
        set -e
        mkdir -p temp
        echo "" > temp/coverage.txt

        go test -coverprofile=temp/profile.out -covermode=atomic $d
        if [ -f temp/profile.out ]; then
            cat temp/profile.out >> temp/coverage.txt
            rm temp/profile.out
        fi
    
    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
